### PR TITLE
Some work on dev5 update.

### PR DESCRIPTION
**Pull request by ineveraskedforthis**

### CODE REVIEW

**Comment by Calandiel** [comment]
I presume ots draft status is intentional and it shouldnt be merged in yet?

**Comment by ineveraskedforthis** [comment]
Yes, I am planning to add more stuff to it.

**Comment by Calandiel** [comment]
Cool beans, looking forward to it!

**Comment by Calandiel** [comment]
Since you guys ( @ineveraskedforthis and @squealingpiggies ) seem to be both making large draft MRs, could we merge them sooner rather than later? Resolving merge conflicts in a 3k+ LOC pull request is hell and we'll likely hit some. It doesn't seem to me like either of yours draft merge requests really needs to be a draft for long - individual features can be split off into smaller pull requests.

**Comment by ineveraskedforthis** [comment]
Okay, sure.
I plan to make another commit related to buildings permissions in next 10 hours and it could be merged.

**Comment by squealingpiggies** [comment]
Admittedly, half of my code is GUI additions / changes / rewrites now. I don't think we touch many of the same files. But I still have a few more days of GUI work before I finish the warband inspector and properly link it to other panels to allow the observer / player to look at other character's warbands.

**Pull request merged**
