### PR TITLE
ensure worldgen port is only available on windows

### PR DESCRIPTION
**Pull request by dsecrieru**

### CODE REVIEW

**Comment by Calandiel** [comment]
Does that work? I don't think there was a global `IS_WINDOWS` in Love2D

**Comment by dsecrieru** [comment]
I added it to the windows run script. Also tested it on wsl and it worked.

**Comment by dsecrieru** [comment]
But I see love2d has functionality for checking os. Maybe I should use that, no idea why I didn't before.

**Comment by Calandiel** [comment]
Thanks, that's more idiomatic for the framework :slightly_smiling_face:

**Pull request merged**
